-- OUR DAY v5.15 - 한 줄 일기
create table if not exists public.daily_diaries (
  id bigint generated by default as identity primary key,
  day date not null,
  person text not null,
  diary text not null,
  created_at timestamptz default now(),
  unique(day, person)
);

alter table public.daily_diaries enable row level security;

drop policy if exists "public read write diaries" on public.daily_diaries;

create policy "public read write diaries"
on public.daily_diaries
for all
to anon
using (true)
with check (true);
