create table if not exists public.daily_songs (
  id bigint generated by default as identity primary key,
  day date not null unique,
  song_title text not null,
  artist text not null,
  reason text,
  mood_tags text[] default '{}',
  youtube_url text,
  youtube_video_id text,
  created_at timestamptz default now()
);
alter table public.daily_songs enable row level security;
drop policy if exists "public read write songs" on public.daily_songs;
create policy "public read write songs" on public.daily_songs for all to anon using (true) with check (true);
