-- OUR DAY Supabase setup
create table if not exists public.daily_answers (
  id bigint generated by default as identity primary key,
  day date not null,
  person text not null,
  answer text not null,
  created_at timestamptz default now(),
  unique(day, person)
);

create table if not exists public.daily_moods (
  id bigint generated by default as identity primary key,
  day date not null,
  person text not null,
  mood text not null,
  created_at timestamptz default now(),
  unique(day, person)
);

create table if not exists public.daily_photos (
  id bigint generated by default as identity primary key,
  day date not null,
  person text not null,
  url text not null,
  created_at timestamptz default now(),
  unique(day, person)
);

create table if not exists public.daily_missions (
  id bigint generated by default as identity primary key,
  day date not null,
  person text not null,
  done boolean default false,
  created_at timestamptz default now(),
  unique(day, person)
);

alter table public.daily_answers enable row level security;
alter table public.daily_moods enable row level security;
alter table public.daily_photos enable row level security;
alter table public.daily_missions enable row level security;

create policy "public read write answers" on public.daily_answers for all to anon using (true) with check (true);
create policy "public read write moods" on public.daily_moods for all to anon using (true) with check (true);
create policy "public read write photos" on public.daily_photos for all to anon using (true) with check (true);
create policy "public read write missions" on public.daily_missions for all to anon using (true) with check (true);

insert into storage.buckets (id, name, public)
values ('couple-photos','couple-photos',true)
on conflict (id) do update set public=true;

create policy "public photo select" on storage.objects for select to anon using (bucket_id='couple-photos');
create policy "public photo insert" on storage.objects for insert to anon with check (bucket_id='couple-photos');
create policy "public photo update" on storage.objects for update to anon using (bucket_id='couple-photos') with check (bucket_id='couple-photos');
